name: Plugin asset/readme update
on:
  workflow_dispatch:
  
jobs:
  trunk:
    name: Push to master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: tuxedo-big-file-uploads # optional, remove if GitHub repo name matches SVN slug, including capitalization
